apiVersion: v1
kind: Service
metadata:
  name: shopsphere-backend
  namespace: gcp-simulation
spec:
  selector:
    app: shopsphere-backend
    env: gcp-simulation
  ports:
    - port: 5000
      targetPort: 5000
  type: ClusterIP
