apiVersion: v1
kind: Service
metadata:
  name: shopsphere-frontend
  namespace: gcp-simulation
spec:
  selector:
    app: shopsphere-frontend
    env: gcp-simulation
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
